from vdu_signal import Signal

SIGNALS_CONFIG = [
    (
        (4, 5, 2, 0, 0),
        {
            "signal_id": "S-1",
            "num_aspects": 2,
            "position": "above",
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-3"],
            "direction_to_control": "right",
        },
    ),
    (
        (1, 7, 0, 0, 0),
        {
            "signal_id": "S-2",
            "num_aspects": 3,
            "position": "below",
            "aspects": ["green", "yellow", "red"],
            "protects_segments": ["T-A2"],
            "direction_to_control": "left",
        },
    ),
    (
        (22, 7, 0, 0, 0),
        {
            "signal_id": "S-3",
            "num_aspects": 4,
            "position": "below",
            "aspects": ["d.yellow", "green", "yellow", "red"],
            "protects_segments": ["T-13"],
            "direction_to_control": "left",
        },
    ),
    (
        (13, 9, 0, 0, 0),
        {
            "signal_id": "S-4",
            "num_aspects": 2,
            "position": "below",
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-27"],
            "direction_to_control": "left",
        },
    ),
    (
        (22, 9, 0, 0, 0),
        {
            "signal_id": "S-5",
            "num_aspects": 2,
            "position": "below",
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-23"],
            "direction_to_control": "left",
        },
    ),
    (
        (25, 13, 0, 0, 0),
        {
            "signal_id": "S-6",
            "num_aspects": 2,
            "position": "below",
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-40"],
            "direction_to_control": "left",
        },
    ),
    (
        (26, 15, 0, 0, 0),
        {
            "signal_id": "S-7",
            "num_aspects": 2,
            "position": "below",
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-42"],
            "direction_to_control": "left",
        },
    ),
    (
        (29, 18, 0, 0, 0),
        {
            "signal_id": "S-8",
            "num_aspects": 2,
            "position": "below",
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-44"],
            "direction_to_control": "left",
        },
    ),
    (
        (30, 19, 0, 0, 0),
        {
            "signal_id": "S-9",
            "num_aspects": 2,
            "position": "below",
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-46"],
            "direction_to_control": "left",
        },
    ),
    (
        (30, 20, 0, 0, 0),
        {
            "signal_id": "S-10",
            "num_aspects": 2,
            "position": "below",
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-51"],
            "direction_to_control": "left",
        },
    ),
    (
        (54, 18, 2, 0, 0),
        {
            "signal_id": "S-11",
            "position": "above",
            "direction_to_control": "right",
            "num_aspects": 2,
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-73"],
        },
    ),
    (
        (58, 19, 2, 0, 0),
        {
            "signal_id": "S-12",
            "position": "above",
            "direction_to_control": "right",
            "num_aspects": 2,
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-58B"],
        },
    ),
    (
        (57, 20, 2, 0, 0),
        {
            "signal_id": "S-13",
            "position": "above",
            "direction_to_control": "right",
            "num_aspects": 2,
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-52B"],
        },
    ),
    (
        (58, 15, 2, 0, 0),
        {
            "signal_id": "S-14",
            "position": "above",
            "direction_to_control": "right",
            "num_aspects": 2,
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-74"],
        },
    ),
    (
        (58, 13, 2, 0, 0),
        {
            "signal_id": "S-15",
            "position": "above",
            "direction_to_control": "right",
            "num_aspects": 2,
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-66"],
        },
    ),
    (
        (60, 9, 2, 0, 0),
        {
            "signal_id": "S-16",
            "position": "above",
            "direction_to_control": "right",
            "num_aspects": 4,
            "aspects": ["d.yellow", "green", "yellow", "red"],
            "protects_segments": ["T-72"],
        },
    ),
    (
        (60, 7, 2, 0, 0),
        {
            "signal_id": "S-17",
            "position": "above",
            "direction_to_control": "right",
            "num_aspects": 2,
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-85"],
        },
    ),
    (
        (55, 5, 2, 0, 0),
        {
            "signal_id": "S-18",
            "position": "above",
            "direction_to_control": "right",
            "num_aspects": 4,
            "aspects": ["d.yellow", "green", "yellow", "red"],
            "protects_segments": ["T-62"],
        },
    ),
    (
        (55, 3, 2, 0, 0),
        {
            "signal_id": "S-19",
            "position": "above",
            "direction_to_control": "right",
            "num_aspects": 2,
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-63"],
        },
    ),
    (
        (52, 0, 2, 0, 0),
        {
            "signal_id": "S-20",
            "position": "above",
            "direction_to_control": "right",
            "num_aspects": 2,
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-68"],
        },
    ),
    (
        (51, -2, 2, 0, 0),
        {
            "signal_id": "S-21",
            "position": "above",
            "direction_to_control": "right",
            "num_aspects": 2,
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-67"],
        },
    ),
    (
        (77, 5, 2, 0, 0),
        {
            "signal_id": "S-22",
            "num_aspects": 4,
            "position": "above",
            "aspects": ["d.yellow", "green", "yellow", "red"],
            "protects_segments": ["T-163"],
            "direction_to_control": "right",
        },
    ),
    (
        (116, 5, 2, 0, 0),
        {
            "signal_id": "S-23",
            "num_aspects": 4,
            "position": "above",
            "aspects": ["d.yellow", "green", "yellow", "red"],
            "protects_segments": ["T-173"],
            "direction_to_control": "right",
        },
    ),
    (
        (189, 5, 2, 0, 0),
        {
            "signal_id": "S-24",
            "num_aspects": 2,
            "position": "above",
            "aspects": ["green", "red"],
            "protects_segments": ["T-191"],
            "direction_to_control": "right",
        },
    ),
    (
        (87, 7, 0, 0, 0),
        {
            "signal_id": "S-25",
            "num_aspects": 3,
            "position": "below",
            "aspects": ["green", "yellow", "red"],
            "protects_segments": ["T-200"],
            "direction_to_control": "left",
        },
    ),
    (
        (83, 11, 0, 0, 0),
        {
            "signal_id": "S-26",
            "num_aspects": 2,
            "position": "below",
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-96B"],
            "direction_to_control": "left",
        },
    ),
    (
        (92, 9, 0, 0, 0),
        {
            "signal_id": "S-27",
            "num_aspects": 2,
            "position": "below",
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-120"],
            "direction_to_control": "left",
        },
    ),
    (
        (116, 9, 2, 0, 0),
        {
            "signal_id": "S-28",
            "num_aspects": 4,
            "position": "above",
            "aspects": ["d.yellow", "green", "yellow", "red"],
            "protects_segments": ["T-207C"],
            "direction_to_control": "right",
        },
    ),
    (
        (117, 7, 0, 0, 0),
        {
            "signal_id": "S-29",
            "num_aspects": 3,
            "position": "below",
            "aspects": ["green", "yellow", "red"],
            "protects_segments": ["T-207"],
            "direction_to_control": "left",
        },
    ),
    (
        (124, 11, 0, 0, 0),
        {
            "signal_id": "S-30",
            "num_aspects": 2,
            "position": "below",
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-125"],
            "direction_to_control": "left",
        },
    ),
    (
        (126, 13, 0, 0, 0),
        {
            "signal_id": "S-31",
            "num_aspects": 2,
            "position": "below",
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-141"],
            "direction_to_control": "left",
        },
    ),
    (
        (124, 15, 0, 0, 0),
        {
            "signal_id": "S-32",
            "num_aspects": 2,
            "position": "below",
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-139"],
            "direction_to_control": "left",
        },
    ),
    (
        (122, 17, 0, 0, 0),
        {
            "signal_id": "S-33",
            "num_aspects": 2,
            "position": "below",
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-137"],
            "direction_to_control": "left",
        },
    ),
    (
        (120, 19, 0, 0, 0),
        {
            "signal_id": "S-34",
            "num_aspects": 2,
            "position": "below",
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-135"],
            "direction_to_control": "left",
        },
    ),
    (
        (150, 13, 2, 0, 0),
        {
            "signal_id": "S-35",
            "num_aspects": 2,
            "position": "above",
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-149"],
            "direction_to_control": "right",
        },
    ),
    (
        (148, 15, 2, 0, 0),
        {
            "signal_id": "S-36",
            "num_aspects": 2,
            "position": "above",
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-148"],
            "direction_to_control": "right",
        },
    ),
    (
        (146, 17, 2, 0, 0),
        {
            "signal_id": "S-37",
            "num_aspects": 2,
            "position": "above",
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-147"],
            "direction_to_control": "right",
        },
    ),
    (
        (144, 19, 2, 0, 0),
        {
            "signal_id": "S-38",
            "num_aspects": 2,
            "position": "above",
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-146"],
            "direction_to_control": "right",
        },
    ),
    (
        (158, 11, 0, 0, 0),
        {
            "signal_id": "S-39",
            "num_aspects": 2,
            "position": "below",
            "aspects": ["yellow", "red"],
            "protects_segments": ["T-132"],
            "direction_to_control": "left",
        },
    ),
    (
        (155, 9, 2, 0, 0),
        {
            "signal_id": "S-40",
            "num_aspects": 3,
            "position": "above",
            "aspects": ["green", "yellow", "red"],
            "protects_segments": ["T-124C"],
            "direction_to_control": "right",
        },
    ),
    (
        (165, 5, 2, 0, 0),
        {
            "signal_id": "S-41",
            "num_aspects": 3,
            "position": "above",
            "aspects": ["green", "yellow", "red"],
            "protects_segments": ["T-191"],
            "direction_to_control": "right",
        },
    ),
    (
        (185, 9, 2, 0, 0),
        {
            "signal_id": "S-42",
            "num_aspects": 2,
            "position": "above",
            "aspects": ["green", "red"],
            "protects_segments": ["T-233"],
            "direction_to_control": "right",
        },
    ),
    (
        (167, 7, 0, 0, 0),
        {
            "signal_id": "S-43",
            "num_aspects": 4,
            "position": "below",
            "aspects": ["d.yellow", "green", "yellow", "red"],
            "protects_segments": ["T-221"],
            "direction_to_control": "left",
        },
    ),
]
